name: github pages

on:
  push:
    branches: 
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
     
     
    - name: Use Node.js 12.x  
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

      
    - run: npm ci
    - run: npm run build

    - name: Deploy wsydxiangwang.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EXTERNAL_REPOSITORY: wsydxiangwang/wsydxiangwang.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: docs/.vuepress/dist
      with:
          emptyCommits: false