name: github pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run deploy

    - name: Deploy wsydxiangwang.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EXTERNAL_REPOSITORY: wsydxiangwang/wsydxiangwang.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: docs/.vuepress/dist
      with:
          emptyCommits: false
