name: github pages

on:
  push:
    branches: 
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    
    

    steps:
    - uses: actions/checkout@v1
     
     
    - name: Use Node.js 12.x  
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Commit files
      run: |
        git config --local user.email "191539823@qq.com"
        git config --local user.name "Libai"
        git commit -m "Add changes" -a
        
    - run: npm ci
    - run: npm run deploy

    - name: Deploy wsydxiangwang.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EXTERNAL_REPOSITORY: wsydxiangwang/wsydxiangwang.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: docs/.vuepress/dist
      with:
          emptyCommits: false
